# Generated by Django 5.0 on 2025-09-22 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('urls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CruxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('form_factor', models.CharField(default='ALL_FORM_FACTORS', max_length=20)),
                ('largest_contentful_paint', models.FloatField(blank=True, null=True)),
                ('first_input_delay', models.FloatField(blank=True, null=True)),
                ('cumulative_layout_shift', models.FloatField(blank=True, null=True)),
                ('first_contentful_paint', models.FloatField(blank=True, null=True)),
                ('interaction_to_next_paint', models.FloatField(blank=True, null=True)),
                ('time_to_first_byte', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('url', 'form_factor', 'created_at')},
            },
        ),
    ]
