# Generated by Django 5.2.6 on 2025-09-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crux_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysissession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='cruxreport',
            unique_together=set(),
        ),
    ]
